stages:
  - validate
  - build
  - test
  - deploy

validate:html:
  stage: validate
  script:
    - echo "Validating HTML"

build:
  stage: build
  script:
    - echo "Building website"

test:
  stage: test
  script:
    - echo "Testing website"

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r *.html *.css *.js public/
  pages: true
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH